#!/usr/bin/env bash
# Build plugin registry index and per-plugin zips.
# Outputs to ./docs/main/
#
# For each top-level dir that contains a *.yml with Stash plugin shape,
# create <id>.zip and add an entry to docs/main/index.yml.

set -euo pipefail

OUT_DIR="docs/main"
rm -rf "$OUT_DIR"
mkdir -p "$OUT_DIR"

# header
cat > "$OUT_DIR/index.yml" << 'HEADER'
# Generated by build.sh — do not edit by hand.
HEADER

for dir in */; do
    dir="${dir%/}"
    # skip meta dirs
    case "$dir" in
        docs|.github|.git|dist) continue ;;
    esac
    # find the plugin manifest
    yml=""
    for candidate in "$dir"/*.yml; do
        if [[ -f "$candidate" ]]; then
            # sanity: must mention `exec:` or be Stash plugin
            if grep -qE '^(exec|interface|hooks|tasks):' "$candidate"; then
                yml="$candidate"
                break
            fi
        fi
    done
    [[ -z "$yml" ]] && continue

    # Plugin ID = YAML filename without extension (matches Stash's internal ID).
    # Stash derives plugin IDs from the manifest filename, so the registry must
    # use the same id or updates don't match the installed plugin.
    id="$(basename "$yml" .yml)"
    # derive version and name from manifest
    name="$(grep -E '^name:' "$yml" | head -1 | sed -E 's/^name:[[:space:]]*//; s/^"(.*)"$/\1/')"
    version="$(grep -E '^version:' "$yml" | head -1 | sed -E 's/^version:[[:space:]]*//; s/^"(.*)"$/\1/')"
    description="$(awk '/^description:/{flag=1; sub(/^description:[[:space:]]*/,""); print; next} flag && /^ +/{print; next} {flag=0}' "$yml" \
                    | tr '\n' ' ' | sed -E 's/[[:space:]]+/ /g; s/^[>|][[:space:]]*//; s/^ //; s/ $//')"
    # escape colons so YAML stays valid
    description="${description//:/ -}"
    name="${name:-$id}"
    version="${version:-0.0.0}"

    echo "packaging $id (v$version)…"

    # zip plugin contents. Exclude caches.
    (cd "$dir" && zip -qrX "../$OUT_DIR/$id.zip" . \
        -x "__pycache__/*" -x "*.pyc" -x ".DS_Store" -x ".git/*")

    sha256="$(sha256sum "$OUT_DIR/$id.zip" | awk '{print $1}')"
    date="$(date -u +%Y-%m-%d)"

    # append entry
    cat >> "$OUT_DIR/index.yml" << ENTRY
- id: $id
  name: $name
  metadata:
    description: $description
  version: $version
  date: $date
  path: $id.zip
  sha256: $sha256
ENTRY
done

echo "index built:"
cat "$OUT_DIR/index.yml"
echo
echo "artifacts:"
ls -la "$OUT_DIR"
